DROP DATABASE IF EXISTS trigames;

CREATE DATABASE trigames;

USE trigames;

DROP TABLE IF EXISTS battleship;
		
CREATE TABLE battleship (
  id INTEGER NOT NULL AUTO_INCREMENT,
  winner VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS tictactoe;
		
CREATE TABLE tictactoe (
  id INTEGER NOT NULL AUTO_INCREMENT,
  victor INTEGER NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS RPS;
		
CREATE TABLE RPS (
  id INTEGER NOT NULL AUTO_INCREMENT, 
  pscore INTEGER NOT NULL,
  cscore INTEGER NOT NULL,
  win INTEGER NOT NULL,
  PRIMARY KEY (id)
);